import { Deal, GroceryProduct, StageConfig } from '../types';

export const STAGES: StageConfig[] = [
  {
    id: 'lead',
    title: '1. Descoberta & Contato',
    description: 'Novos vizinhos, pediu encarte ou mandou "olá" no WhatsApp',
    color: 'text-amber-700',
    bgLight: 'bg-amber-50',
    borderLight: 'border-amber-200',
    icon: 'Sparkles',
  },
  {
    id: 'contacted',
    title: '2. Interesse & Cotação',
    description: 'Pediu preços do hortifruti ou lista de compras da semana',
    color: 'text-blue-700',
    bgLight: 'bg-blue-50',
    borderLight: 'border-blue-200',
    icon: 'ShoppingCart',
  },
  {
    id: 'proposal',
    title: '3. Cesta & Orçamento',
    description: 'Pedido montado, conferindo itens e taxa de entrega',
    color: 'text-indigo-700',
    bgLight: 'bg-indigo-50',
    borderLight: 'border-indigo-200',
    icon: 'FileText',
  },
  {
    id: 'won',
    title: '4. Venda Concluída',
    description: 'Pago e entregue ou retirado no balcão da mercearia',
    color: 'text-emerald-700',
    bgLight: 'bg-emerald-50',
    borderLight: 'border-emerald-200',
    icon: 'CheckCircle2',
  },
  {
    id: 'loyalty',
    title: '5. Fidelização & Recompra',
    description: 'Clientes recorrentes (feira semanal / reposição de despensa)',
    color: 'text-purple-700',
    bgLight: 'bg-purple-50',
    borderLight: 'border-purple-200',
    icon: 'Repeat',
  },
  {
    id: 'lost',
    title: '6. Perdido / Desistência',
    description: 'Comprou em outro mercado, fora do raio de entrega ou sem estoque',
    color: 'text-rose-700',
    bgLight: 'bg-rose-50',
    borderLight: 'border-rose-200',
    icon: 'XCircle',
  },
];

export const GROCERY_CATALOG: GroceryProduct[] = [
  { id: 'p1', name: 'Arroz Tipo 1 Camil 5kg', category: 'mercearia', default_unit: 'pct', price: 29.90 },
  { id: 'p2', name: 'Feijão Carioca Tipo 1 1kg', category: 'mercearia', default_unit: 'pct', price: 8.50 },
  { id: 'p3', name: 'Óleo de Soja Soya 900ml', category: 'mercearia', default_unit: 'un', price: 6.90 },
  { id: 'p4', name: 'Café Torrado e Moído 500g', category: 'mercearia', default_unit: 'pct', price: 18.90 },
  { id: 'p5', name: 'Açúcar Refinado 1kg', category: 'mercearia', default_unit: 'pct', price: 4.80 },
  { id: 'p6', name: 'Leite Integral UHT 1L', category: 'frios_laticinios', default_unit: 'lt', price: 5.20 },
  { id: 'p7', name: 'Cartela de Ovos Brancos 30un', category: 'mercearia', default_unit: 'cx', price: 19.90 },
  { id: 'p8', name: 'Banana Prata Selecionada (kg)', category: 'hortifruti', default_unit: 'kg', price: 6.99 },
  { id: 'p9', name: 'Tomate Italiano Especial (kg)', category: 'hortifruti', default_unit: 'kg', price: 7.90 },
  { id: 'p10', name: 'Batata Monalisa Lavada (kg)', category: 'hortifruti', default_unit: 'kg', price: 5.80 },
  { id: 'p11', name: 'Cebola Amarela Nacional (kg)', category: 'hortifruti', default_unit: 'kg', price: 4.90 },
  { id: 'p12', name: 'Maçã Gala Fresca (kg)', category: 'hortifruti', default_unit: 'kg', price: 9.90 },
  { id: 'p13', name: 'Queijo Mussarela Fatiado (kg)', category: 'frios_laticinios', default_unit: 'kg', price: 42.00 },
  { id: 'p14', name: 'Presunto Cozido Fatiado (kg)', category: 'frios_laticinios', default_unit: 'kg', price: 34.00 },
  { id: 'p15', name: 'Pão Francês Quentinho (kg)', category: 'padaria', default_unit: 'kg', price: 16.90 },
  { id: 'p16', name: 'Refrigerante Coca-Cola 2L', category: 'bebidas', default_unit: 'un', price: 9.99 },
  { id: 'p17', name: 'Detergente Líquido Neutro 500ml', category: 'limpeza', default_unit: 'un', price: 2.79 },
  { id: 'p18', name: 'Sabão em Pó Omo Lavagem Perfeita 800g', category: 'limpeza', default_unit: 'pct', price: 14.50 },
  { id: 'p19', name: 'Cesta Básica Completa Mercearia (18 itens)', category: 'mercearia', default_unit: 'cx', price: 169.00 },
  { id: 'p20', name: 'Kit Feira da Semana (Verduras + Frutas da Estação)', category: 'hortifruti', default_unit: 'cx', price: 49.90 },
  { id: 'p21', name: 'Carvão Vegetal para Churrasco 3kg', category: 'mercearia', default_unit: 'pct', price: 16.00 },
  { id: 'p22', name: 'Linguiça Toscana Sadia (kg)', category: 'carnes', default_unit: 'kg', price: 22.90 },
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-001',
    customer_name: 'Dona Maria de Lourdes',
    customer_phone: '11984210034',
    customer_neighborhood: 'Vila Esperança',
    customer_address: 'Rua das Camélias, 142 - Casa 2',
    stage: 'lead',
    source: 'whatsapp',
    delivery_type: 'delivery',
    payment_method: 'pix',
    notes: 'Pediu a tabela da Feira da Quarta no WhatsApp. Quer saber se tem banana prata bem madura.',
    items: [
      { id: 'i1', name: 'Kit Feira da Semana (Verduras + Frutas da Estação)', quantity: 1, unit: 'cx', unit_price: 49.90, total: 49.90 },
      { id: 'i2', name: 'Banana Prata Selecionada (kg)', quantity: 1.5, unit: 'kg', unit_price: 6.99, total: 10.49 },
    ],
    total_value: 60.39,
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'deal-002',
    customer_name: 'Seu Raimundo (Pedreiro da Obra)',
    customer_phone: '11971239981',
    customer_neighborhood: 'Jardim Primavera',
    customer_address: 'Obra na Rua 15 de Novembro, 88',
    stage: 'contacted',
    source: 'balcao',
    delivery_type: 'pickup',
    payment_method: 'dinheiro',
    notes: 'Passou de manhã cedo querendo montar lanche e café para 4 ajudantes da obra.',
    items: [
      { id: 'i3', name: 'Pão Francês Quentinho (kg)', quantity: 1, unit: 'kg', unit_price: 16.90, total: 16.90 },
      { id: 'i4', name: 'Queijo Mussarela Fatiado (kg)', quantity: 0.3, unit: 'kg', unit_price: 42.00, total: 12.60 },
      { id: 'i5', name: 'Presunto Cozido Fatiado (kg)', quantity: 0.3, unit: 'kg', unit_price: 34.00, total: 10.20 },
      { id: 'i6', name: 'Refrigerante Coca-Cola 2L', quantity: 2, unit: 'un', unit_price: 9.99, total: 19.98 },
    ],
    total_value: 59.68,
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'deal-003',
    customer_name: 'Família Silva (Juliana)',
    customer_phone: '11993448120',
    customer_neighborhood: 'Centro',
    customer_address: 'Av. Brasil, 450 - Apto 32',
    stage: 'proposal',
    source: 'whatsapp',
    delivery_type: 'delivery',
    payment_method: 'pix',
    notes: 'Cesta do mês + produtos de limpeza. Pediu para entregar após as 18h com troco se for em dinheiro, mas fechou no Pix.',
    items: [
      { id: 'i7', name: 'Cesta Básica Completa Mercearia (18 itens)', quantity: 1, unit: 'cx', unit_price: 169.00, total: 169.00 },
      { id: 'i8', name: 'Cartela de Ovos Brancos 30un', quantity: 1, unit: 'cx', unit_price: 19.90, total: 19.90 },
      { id: 'i9', name: 'Sabão em Pó Omo Lavagem Perfeita 800g', quantity: 2, unit: 'pct', unit_price: 14.50, total: 29.00 },
      { id: 'i10', name: 'Detergente Líquido Neutro 500ml', quantity: 3, unit: 'un', unit_price: 2.79, total: 8.37 },
    ],
    total_value: 226.27,
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'deal-004',
    customer_name: 'Churrasco da Turma (Marcos)',
    customer_phone: '11985552341',
    customer_neighborhood: 'Bairro Alto',
    customer_address: 'Rua Bela Vista, 310',
    stage: 'won',
    source: 'indicacao',
    delivery_type: 'delivery',
    payment_method: 'cartao_credito',
    notes: 'Kit churrasco de domingo. Venda entregue na hora e paga com maquininha na porta.',
    items: [
      { id: 'i11', name: 'Linguiça Toscana Sadia (kg)', quantity: 4, unit: 'kg', unit_price: 22.90, total: 91.60 },
      { id: 'i12', name: 'Carvão Vegetal para Churrasco 3kg', quantity: 3, unit: 'pct', unit_price: 16.00, total: 48.00 },
      { id: 'i13', name: 'Refrigerante Coca-Cola 2L', quantity: 4, unit: 'un', unit_price: 9.99, total: 39.96 },
      { id: 'i14', name: 'Tomate Italiano Especial (kg)', quantity: 1.5, unit: 'kg', unit_price: 7.90, total: 11.85 },
      { id: 'i15', name: 'Cebola Amarela Nacional (kg)', quantity: 1, unit: 'kg', unit_price: 4.90, total: 4.90 },
    ],
    total_value: 196.31,
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'deal-005',
    customer_name: 'Dona Neide (Cliente Mensalista)',
    customer_phone: '11977712390',
    customer_neighborhood: 'Vila Esperança',
    customer_address: 'Travessa dos Ipês, 15',
    stage: 'loyalty',
    source: 'whatsapp',
    delivery_type: 'delivery',
    payment_method: 'caderneta_fiado',
    notes: 'Cliente fiel há 4 anos. Repõe hortifruti toda terça e quinta. Sempre anota na caderneta e acerta no 5º dia útil.',
    last_purchase_date: new Date(Date.now() - 3600000 * 48).toISOString(),
    items: [
      { id: 'i16', name: 'Arroz Tipo 1 Camil 5kg', quantity: 1, unit: 'pct', unit_price: 29.90, total: 29.90 },
      { id: 'i17', name: 'Feijão Carioca Tipo 1 1kg', quantity: 2, unit: 'pct', unit_price: 8.50, total: 17.00 },
      { id: 'i18', name: 'Café Torrado e Moído 500g', quantity: 2, unit: 'pct', unit_price: 18.90, total: 37.80 },
      { id: 'i19', name: 'Leite Integral UHT 1L', quantity: 6, unit: 'lt', unit_price: 5.20, total: 31.20 },
      { id: 'i20', name: 'Batata Monalisa Lavada (kg)', quantity: 2, unit: 'kg', unit_price: 5.80, total: 11.60 },
    ],
    total_value: 127.50,
    created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: 'deal-006',
    customer_name: 'Carlos Condomínio Green',
    customer_phone: '11961122334',
    customer_neighborhood: 'Jardins (Fora da Área)',
    customer_address: 'Rodovia Km 18, Cond. Solar',
    stage: 'lost',
    source: 'whatsapp',
    delivery_type: 'delivery',
    payment_method: 'pix',
    lost_reason: 'Endereço muito distante (distância > 12km, motoboy da mercearia não atende)',
    notes: 'Pediu entrega de compras pesadas mas ficava a 15km de distância. Sugerido retirar no balcão, mas preferiu não fechar.',
    items: [
      { id: 'i21', name: 'Cesta Básica Completa Mercearia (18 itens)', quantity: 2, unit: 'cx', unit_price: 169.00, total: 338.00 },
    ],
    total_value: 338.00,
    created_at: new Date(Date.now() - 3600000 * 36).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 18).toISOString(),
  }
];
